=== rsanchez-wsu/sp16-ceg3120/RecentQueries.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT queries(query, query, query, query, query, query, query, query, query, query, query, query, query, query, query, query, query, query, query, query)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>
<!ELEMENT query(#PCDATA)>

=== rsanchez-wsu/sp16-ceg3120/RecentQueries.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profiles PUBLIC "//UNKNOWN/" "RecentQueries.dtd">

<queries>

	<query num="1"> </query>
	<query num="2"> </query>
	<query num="3"> </query>
	<query num="4"> </query>
	<query num="5"> </query>
	<query num="6"> </query>
	<query num="7"> </query>
	<query num="8"> </query>
	<query num="9"> </query>
	<query num="10"> </query>
	<query num="11"> </query>
	<query num="12"> </query>
	<query num="13"> </query>
	<query num="14"> </query>
	<query num="15"> </query>
	<query num="16"> </query>
	<query num="17"> </query>
	<query num="18"> </query>
	<query num="19"> </query>
	<query num="20"> </query>

</queries>
